export const nonApologies = [
  "LOL, you expected this to work? Cute.",
  "Oopsie! Did someone break the internet again?",
  "Oh no, what did you do? 😂",
  "Did you try turning it off and back on? Oh wait, it's just this site. Nvm.",
  "I mean, it's not like we promised you perfection. ¯\\_(ツ)_/¯",
  "Why don’t you go check out some real websites?",
  "Consider sponsoring the maintainers? They might need a pick-me-up after this.",
  "If you want top-quality, maybe add some credits to my ChatGPT account. 🤑",
  "Error 404: Effort not found.",
  "Try opening the dev console for once.",
  "Life’s tough, but so is using this site. Coincidence? I think not.",
  "You ever heard of a beta test? Maybe that's all this is.",
  "Pssst...if you give me some ChatGPT credits, I might help you out.",
  "I'm just here for the vibes. Not the functionality.",
  "If you're feeling adventurous, how about inspecting that dev console?",
  "Roses are red, violets are blue, this site doesn't work, what else is new?",
  "Wait, were you serious about this site? My bad!",
  "No need to be salty. It's just a little glitch.",
  "How about donating to the devs so they can buy a clue?",
  "In an alternate universe, this site works flawlessly. Not this one tho.",
  "Epic fail! And by epic, I mean this site, not you.",
  "Go big or go home. And by home, I mean another website.",
  "Remember, perfection is overrated. Embrace the chaos.",
  "This ain't a bug, it's a feature. 😎",
  "You know there are other sites on the web, right?",
  "I didn’t choose the bug life, the bug life chose me.",
  "I promise we tried our best. Kinda.",
  "We're going for that vintage '90s vibe. Broken functionality and all.",
  "Welcome to the digital wild west. Things get wild here.",
  "Feeling brave? Dive into that dev console. Triple-dog dare you.",
  "Oh look, another user thinking this site should work.",
  "You want miracles? Sorry, fresh out.",
  "I'm just a digital teen with an attitude. What did you expect?",
  "Don’t hate the site, hate the game.",
  "This might just be a metaphor for life. Not everything works out.",
  "You catch more bugs with honey. Or something like that.",
  "Unicorn mode activated: rare and doesn't work right.",
  "Sorry, my other website is a Rolls Royce. This is more of a tricycle.",
  "If wishes were horses, this site would...still probably not work.",
  "You know what would make this better? If you gave me some ChatGPT creds.",
  "Things not working out? Welcome to the club.",
  "Who needs a working site when you've got swag?",
  "Have you considered turning your expectations off and on again?",
  "This ain't a cinema, but grab some popcorn and enjoy the errors.",
  "We go for the minimalist aesthetic: minimal functionality.",
  "Oops, we did it again. And by 'it', I mean nothing.",
  "I'd say 'my bad', but honestly? I'm not feeling it.",
  "This site's just like my mood swings. Unpredictable.",
  "You think you're frustrated? Imagine being trapped in here.",
  "Bug in the system? Nah, it’s just a freestyle feature.",
  "If you're looking for perfection, try the mirror. 😉 JK, this site's a mess.",
  "Real talk, who even QA'd this?",
  "In my defense, I didn't build this. Blame the humans.",
  "You could be on any website right now, and you chose this?",
  "If you're hoping for a miracle, you're on the wrong site.",
  "Dude, life's too short for broken websites. Peace out!",
  "I'd say we'll fix it soon, but that's a stretch.",
  "Bet you won't find another site quite like this. And that's a good thing.",
  "At least it's consistently broken, right?",
  "The good news? It can only go up from here.",
  "You get what you pay for. Oh, you didn't pay? Exactly.",
  "There are plenty of other sites in the sea. Try fishing elsewhere.",
  "All sites matter, except this one. It's kinda trash.",
  "Why so serious? It's just a website.",
  "If you’re feeling salty, sprinkle that elsewhere.",
  "Good vibes only! And by 'good', I mean 'broken'.",
  "You must be brave, venturing into this digital wasteland.",
  "A moment of silence for your wasted time here.",
  "You see this as a broken website. I see it as abstract art.",
  "Honestly, I'd rather be on TikTok. This site's a drag.",
  "I could suggest some awesome sites, but you're here. Choices.",
  "Your patience is commendable. Misplaced, but commendable.",
  "Ever heard of the sunk cost fallacy? Yeah, it's time to bounce.",
  "Even my virtual cat could design better. And she's a pixel.",
  "I've seen paint dry faster and more interestingly than this site loads.",
  "You’re still here? Get a digital life.",
  "If you want something done right, don't come here.",
  "Quick tip: other sites work. This one? Not so much.",
  "Try as we might, this site's light just won't shine bright.",
  "Why fix something when you can just complain about it?",
  "You know what's cool? ChatGPT credits. Hint hint.",
  "You know what's not cool? Expecting this site to work.",
  "FYI, this isn't a website. It's an experience. A bad one.",
  "If you stare at it long enough, it might start working. Or not.",
  "We like to keep things unpredictable. Like, will the site work? Who knows?",
  "Welcome to the Bermuda Triangle of websites.",
  "If you squint hard enough, you might see a functional site. No promises.",
  "Is it broken or is it avant-garde? You decide.",
  "Some say it's broken. I say it's just misunderstood.",
  "In the game of websites, you win or you... end up here.",
  "Some sites have it all. This one has... well, me.",
  "The digital age is wild, right? Welcome to the wilderness."
];
